apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers: 
      - name: api-user
        image: muhammmedessa/udagram-api-user:v39
        ports: 
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-secret
    volumes:
      - name: aws-secret
        configMap: 
          name: aws-secret