apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QUtJQVlGRFgyVEtRN0lJS1ZET0s=
  aws_secret_access_key: NzArRkJLenlvOU84OUFQUDZrMkFEUGlPMnprRUc2NlpHQ3pCMU5uQQ==
  aws_session_token: FwoGZXIvYXdzEBgaDJVtIExDkLghercAjiK7AZtmfW8bsn0CCA7KLSPgWFyEKYLvsvggNCg5sLeUIPaCy3r/lTU4yqPwGrZK7QWErDk5nLxwZRQwd0Muziedv6r1iphivZ4Id6TuD8Vof+HXZDYbkK0zmPX47kSjpn4C4qkwAeZXfHVaJ8UYA9iGsB1e3XJnc94zmNiIXDpm8kOnrBvCgrZVvP4pifgEew2JgSi2ejByo6P8JKhie/5WggSb8rq+BsvsSoVaUQUa5JamFujjRtaB3vMoeGQo5OaZmwYyLTen4x28YWBX4QriWmrX9/j4FCwx/bfIwGeu/Ue29iEpR180NUvFxmKeBVoQQw==
  